version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:latest
    ports:
      - "5460:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./app/db:/docker-entrypoint-initdb.d
