version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    env_file:
      - .env
    depends_on:
      - local
    volumes:
      - ./app:/app

  local:
    image: postgres:latest
    ports:
      - "5460:5432"
    environment:
      POSTGRES_USER: mantto
      POSTGRES_PASSWORD: Sistemas0
      POSTGRES_DB: Catalogo
    volumes:
      - ./app/local:/docker-entrypoint-initlocal.d
